export const testValues = [
    { id: 1, name: "Graspus graspus" },
    { id: 2, name: "Grus rubicundus" },
    { id: 3, name: "Speothos vanaticus" },
    { id: 4, name: "Charadrius tricollaris" },
    { id: 5, name: "Sciurus vulgaris" },
    { id: 6, name: "Ateles paniscus" },
    { id: 7, name: "Bucorvus leadbeateri" },
    { id: 8, name: "Bubulcus ibis" },
    { id: 9, name: "Physignathus cocincinus" },
    { id: 10, name: "Phoca vitulina" },
    { id: 11, name: "unavailable" },
    { id: 12, name: "Zenaida galapagoensis" },
    { id: 13, name: "Pseudalopex gymnocercus" },
    { id: 14, name: "Terathopius ecaudatus" },
    { id: 15, name: "Eumetopias jubatus" },
    { id: 16, name: "Callorhinus ursinus" },
    { id: 17, name: "Tamiasciurus hudsonicus" },
    { id: 18, name: "Dasyurus viverrinus" },
    { id: 19, name: "Madoqua kirkii" },
    { id: 20, name: "Hystrix cristata" },
];
